### PR TITLE
Implement Works section and About myself section for the mobile version

### PR DESCRIPTION
**Pull request by Roathy**
**In this branch I did:**

- Add Work section to the website
- Add About Myself section to the website
- Update style.css
- Implement CSS flexbox
- Implement CSS grid
- Fix the branch name to make it descriptive
- Fix index.html issues

### CODE REVIEW

**Comment by TuyishimireEric** [comment]
# INVALID ❌ ❌ ❌
### Hi @Roathy 3  👋

While you made a great effort in this project, I can't go ahead and review your code.

## Invalid Code Review Request ❌
You have submitted a project that doesn't have a professional README😨, Kindly configure use the Microverse template and submit again once you are done 🙏  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Kindly create  a new PR that follows the Gitflow approach

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

---
_Invalid Code Review Request does not count into the code reviews limit._

**Comment by Roathy** [comment]
> # INVALID ❌ ❌ ❌
> ### Hi @Roathy 3 👋
> While you made a great effort in this project, I can't go ahead and review your code.
> 
> ## Invalid Code Review Request ❌
> You have submitted a project that doesn't have a professional README😨, Kindly configure use the Microverse template and submit again once you are done 🙏
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Kindly create a new PR that follows the Gitflow approach
> 
> Cheers and Happy coding!👏👏👏
> 
> ✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.
> 
> ⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
> 
> _Invalid Code Review Request does not count into the code reviews limit._

Hello @TuyishimireEric, I used the template provided by Microverse by one of the previous activities and filled in with information about the project. Could you please be more specific about what is wrong or what need to add/modify? Thank you

**Comment by TuyishimireEric** [comment]
Kindly provide the links related to your project such as the License, your social media links, the table of contents, and the issue page, and submit again for a review 🙏

**Comment by Roathy** [comment]
> Kindly provide the links related to your project such as the License, your social media links, the table of contents, and the issue page, and submit again for a review 🙏

Ok, thank you, I'll work on it. Could you please specify what "issue page" means?

**Comment by TuyishimireEric** [comment]
This is the issue page of this repo: https://github.com/Roathy/Portfolio/issues

**Pull request closed without merging**
